{Compiler Directives...Adjust As You See Fit...}
{.$DEFINE LocalMAX}
{$A+}
{$B-}
{$E+}
{$F+}
{$G+}
{$I-}
{$L-}
{$N-}
{$O+}
{$P-}
{$Q-}
{$R-}
{$S-}
{$T-}
{$V-}
{$X+}

(*
{Compiler Directives...Adjust As You See Fit...}
{$A+}   {Align data on word boundaries.}
{$B-}   {   Complete Boolean evaluation}
{$D-}   {     Debugging Information Off}
{$E+}   {                  Emulation On}
{$F-}   {           Force Far Calls Off}
{$G+}   {        286 Generation Code On}
{$I-}   {               I/O Checking On}
{$L+}   {              Local Symbals On}
{$N+}   {      Numeric Co-processor Off}
{$O+}   {    Overlay Code Generation On}
{$P-}   {           Open Parameters Off}
{$Q-}   {         Overflow Checking Off}
{$R-}   {            Range Checking Off}
{$S+}   {             Stack Checking On}
{$T-}   {     Type-checked Pointers Off}
{$V-}   {   Relaxed var-string checking}
{$X+}   {    Extended syntax support on}
*)